-- Instrucciones de Creacion de las Tablas y sus Relaciones
USE DB_ASIGNACION_ACTIVOS_FIJOS;
GO

-- Esquema de Segunidad
CREATE TABLE Seguridad.SYS_ROL
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_ROL_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL,
)
GO

CREATE TABLE Seguridad.SYS_USUARIOS
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_USUARIOS_ID PRIMARY KEY CLUSTERED(ID),	
	ID_ROL INT NOT NULL,
		CONSTRAINT FX_SYS_USUARIOS_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES Seguridad.SYS_ROL(ID),
	xUID NVARCHAR(200) NOT NULL,
	xPWD NVARCHAR(200) NOT NULL,
	NOMBRE_COMPLETO NVARCHAR(1000) NOT NULL,
	ESTADO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL,
	FECHA_MOD DATE NOT NULL,
)
GO

CREATE TABLE Seguridad.SYS_OPCIONES
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_OPCIONES_ID PRIMARY KEY CLUSTERED(ID),
	CODIGO_01 NVARCHAR(200) NOT NULL,
	CODIGO_02 NVARCHAR(200) NOT NULL,
	DESCRIPCION NVARCHAR(200) NOT NULL,
	NIVEL INT NOT NULL,
	TIPO NVARCHAR(50) NOT NULL,
)

GO

CREATE TABLE Seguridad.SYS_ACCESOS
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_ACCESOS_ID PRIMARY KEY CLUSTERED(ID),	
	ID_OPCIONES INT NOT NULL,
		CONSTRAINT FX_SYS_ACCESOS_ID_OPCION FOREIGN KEY (ID_OPCIONES) REFERENCES Seguridad.SYS_OPCIONES(ID),	
	ID_ROL INT NOT NULL,
		CONSTRAINT FX_SYS_ACCESOS_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES Seguridad.SYS_ROL(ID),
	ID_USUARIO INT NOT NULL DEFAULT 1,
	EJECUTAR INT NOT NULL DEFAULT 0,
	VISUALIZAR INT NOT NULL DEFAULT 0,
	BORRAR INT NOT NULL DEFAULT 0,
	IMPRIMIR INT NOT NULL DEFAULT 0,
	INSERTAR INT NOT NULL DEFAULT 0,
	ACTUALIZAR INT NOT NULL DEFAULT 0,
)

GO

CREATE TABLE Seguridad.SYS_SESION
(
	ID NUMERIC(38, 0) NOT NULL,
		CONSTRAINT PK_SYS_SESION_ID PRIMARY KEY CLUSTERED(ID),
	ID_USUARIO INT NOT NULL,
		CONSTRAINT FX_SYS_SESION_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES Seguridad.SYS_USUARIOS(ID),
	ID_ROL INT NOT NULL,
		CONSTRAINT FX_SYS_SESION_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES Seguridad.SYS_ROL(ID),
	FECHA DATE NOT NULL,
	ESTADO INT NOT NULL,
)

GO

CREATE TABLE Seguridad.SYS_BITACORA
(
	ID NUMERIC(38, 0) NOT NULL,
		CONSTRAINT PK_SYS_BITACORA_ID PRIMARY KEY CLUSTERED(ID),
	ID_SESION NUMERIC(38, 0) NOT NULL,
		CONSTRAINT FX_SYS_BITACORA_ID_SESION FOREIGN KEY (ID_SESION) REFERENCES Seguridad.SYS_SESION(ID),
	VENTANA NVARCHAR(200) NOT NULL,
	ANTES NVARCHAR(1000),
	DESPUES NVARCHAR(1000),
	HORA NVARCHAR(50),
)

GO

CREATE TABLE Seguridad.SYS_FIRMAS_DOCUMENTOS
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_FIRMAS_DOCUMENTOS_ID PRIMARY KEY CLUSTERED(ID),
	NOMBRE_COMPLETO NVARCHAR(200) NOT NULL DEFAULT '',
	CARGO_OCUPACIONAL NVARCHAR(1000) NOT NULL DEFAULT '',
	ACTIVO INT NOT NULL,
)

GO

CREATE TABLE Seguridad.SYS_FOTOS
(
	ID INT NOT NULL,
		CONSTRAINT PK_SYS_FOTOS_ID PRIMARY KEY CLUSTERED(ID),
	LOGOS NVARCHAR(1000) NOT NULL DEFAULT '',
	ACTIVO INT NOT NULL,
)

GO



-- Esquema Funcional
CREATE TABLE Activos_Fijos.TBL_AREA_FUNCIONAL
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_AREA_FUNCIONAL_ID PRIMARY KEY CLUSTERED(ID),
	CODIGO NVARCHAR(50) NOT NULL DEFAULT '',
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_CARGO_OCUPACIONAL
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_CARGO_OCUPACIONAL_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_MARCA
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_MARCA_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_MODELO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_MARCAS_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_CLASE
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_CLASE_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_COLOR
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_COLOR_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_TIPO_ALTA
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_TIPO_ALTA_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_PROCEDENCIA
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_PROCEDENCIA_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_TIPO_MOVIMIENTO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_TIPO_MOVIMIENTO_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO


-- TIPO DE ENTIDAD: NATURAL o JURIDICO
CREATE TABLE Activos_Fijos.TBL_TIPO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_TIPO_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(200) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

-- TIPO DE CONTACTO: REPRESENTANTE, APODERADO GENERAL, APODERADO ESPECIAL,
CREATE TABLE Activos_Fijos.TBL_TIPO_CONTACTO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_TIPO_CONTACTO_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(200) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_SEXO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_SEXO_ID PRIMARY KEY CLUSTERED(ID),
	DESCRIPCION NVARCHAR(200) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO


CREATE TABLE Activos_Fijos.TBL_EMPLEADO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_EMPLEADO_ID PRIMARY KEY CLUSTERED(ID),
	ID_AREA_FUNCIONAL INT NOT NULL,
		CONSTRAINT FX_TBL_EMPLEADO_ID_AREA_FUNCIONAL FOREIGN KEY (ID_AREA_FUNCIONAL) REFERENCES Activos_Fijos.TBL_AREA_FUNCIONAL(ID),
	ID_CARGO_OCUPACIONAL INT NOT NULL,
		CONSTRAINT FX_TBL_EMPLEADO_ID_CARGO_OCUPACIONAL FOREIGN KEY (ID_CARGO_OCUPACIONAL) REFERENCES Activos_Fijos.TBL_CARGO_OCUPACIONAL(ID),
	ID_SEXO INT NOT NULL,
		CONSTRAINT FX_TBL_EMPLEADO_ID_SEXO FOREIGN KEY (ID_SEXO) REFERENCES Activos_Fijos.TBL_SEXO(ID),
	PRIMER_NOMBRE NVARCHAR(200) NOT NULL DEFAULT '',
	SEGUNDO_NOMBRE NVARCHAR(200) DEFAULT '',
	PRIMER_APELLIDO NVARCHAR(200) NOT NULL DEFAULT '',
	SEGUNDO_APELLIDO NVARCHAR(200) DEFAULT '',
	CEDULA NVARCHAR(50) NOT NULL DEFAULT '',
	NO_INSS NVARCHAR(50) NOT NULL DEFAULT '',
	DIRECCION NVARCHAR(1000) DEFAULT '',
	TELEFONOS NVARCHAR(200) DEFAULT '', 
	EMAIL NVARCHAR(1000) DEFAULT '',
	INGRESO DATE NOT NULL DEFAULT GETDATE(),
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO


CREATE TABLE Activos_Fijos.TBL_PROVEEDOR
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_PROVEEDOR_ID PRIMARY KEY CLUSTERED(ID),
	ID_TIPO INT NOT NULL,
		CONSTRAINT FX_TBL_PROVEEDOR_ID_TIPO FOREIGN KEY (ID_TIPO) REFERENCES Activos_Fijos.TBL_TIPO(ID),	
	ID_SEXO INT NOT NULL,
		CONSTRAINT FX_TBL_PROVEEDOR_ID_SEXO FOREIGN KEY (ID_SEXO) REFERENCES Activos_Fijos.TBL_SEXO(ID),	
	IDENTIFICACION NVARCHAR(50) NOT NULL DEFAULT '',
	PRIMER_APELLIDO NVARCHAR(250) NOT NULL DEFAULT '',
	SEGUNDO_APELLIDO NVARCHAR(250) DEFAULT '',
	PRIMER_NOMBRE NVARCHAR(250) NOT NULL DEFAULT '',
	SEGUNDO_NOMBRE NVARCHAR(250) DEFAULT '',
	RAZON_SOCIAL NVARCHAR(200) NOT NULL DEFAULT '',
	DIRECCION NVARCHAR(1000) DEFAULT '',
	TELEFONOS NVARCHAR(200) DEFAULT '',
	EMAIL NVARCHAR(1000) DEFAULT '',
	INGRESO DATE NOT NULL DEFAULT GETDATE(),
	ESTADO INT NOT NULL DEFAULT 1,
	ID_USUARIO INT NOT NULL DEFAULT 1,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
)
GO

CREATE TABLE Activos_Fijos.TBL_CONTACTO_PROVEEDOR
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_CONTACTO_PROVEEDOR_ID PRIMARY KEY CLUSTERED(ID),
	ID_PROVEEDOR INT NOT NULL,
		CONSTRAINT FX_TBL_CONTACTO_PROVEEDOR_ID_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES Activos_Fijos.TBL_PROVEEDOR(ID),
	ID_TIPO_CONTACTO INT NOT NULL,
		CONSTRAINT FX_TBL_CONTACTO_PROVEEDOR_ID_TIPO_CONTACTO FOREIGN KEY (ID_TIPO_CONTACTO) REFERENCES Activos_Fijos.TBL_TIPO_CONTACTO(ID),
	ID_SEXO INT NOT NULL,
		CONSTRAINT FX_TBL_CONTACTO_PROVEEDOR_ID_SEXO FOREIGN KEY (ID_SEXO) REFERENCES Activos_Fijos.TBL_SEXO(ID),
	IDENTIFICACION NVARCHAR(50) NOT NULL DEFAULT '',
	PRIMER_APELLIDO NVARCHAR(250) NOT NULL DEFAULT '',
	SEGUNDO_APELLIDO NVARCHAR(250) DEFAULT '',
	PRIMER_NOMBRE NVARCHAR(250) NOT NULL DEFAULT '',
	SEGUNDO_NOMBRE NVARCHAR(250) DEFAULT '',
	DIRECCION NVARCHAR(1000) DEFAULT '',
	TELEFONOS NVARCHAR(200) DEFAULT '',
	EMAIL NVARCHAR(1000) DEFAULT '',
	INGRESO DATE NOT NULL DEFAULT GETDATE(),
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_ARTICULO
(
	ID INT NOT NULL,
		CONSTRAINT PK_TBL_ARTICULO_ID PRIMARY KEY CLUSTERED(ID),
	ID_PROVEEDOR INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES Activos_Fijos.TBL_PROVEEDOR(ID),
	ID_TIPO_ALTA INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_TIPO_ALTA FOREIGN KEY (ID_TIPO_ALTA) REFERENCES Activos_Fijos.TBL_TIPO_ALTA(ID),
	ID_PROCEDENCIA INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_PROCEDENCIA FOREIGN KEY (ID_PROCEDENCIA) REFERENCES Activos_Fijos.TBL_PROCEDENCIA(ID),
	ID_MARCA INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_MARCA FOREIGN KEY (ID_MARCA) REFERENCES Activos_Fijos.TBL_MARCA(ID),
	ID_MODELO INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_MODELO FOREIGN KEY (ID_MODELO) REFERENCES Activos_Fijos.TBL_MODELO(ID),
	ID_CLASE INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_CLASE FOREIGN KEY (ID_CLASE) REFERENCES Activos_Fijos.TBL_CLASE(ID),
	ID_COLOR INT NOT NULL,
		CONSTRAINT FX_TBL_ARTICULO_ID_COLOR FOREIGN KEY (ID_COLOR) REFERENCES Activos_Fijos.TBL_COLOR(ID),
	REF_CODIGO_SIBE NVARCHAR(100) NOT NULL DEFAULT '',
	REF_NUM_SERIE NVARCHAR(100) NOT NULL DEFAULT '',
	REF_NUM_FACTURA NVARCHAR(100) NOT NULL DEFAULT '',
	REF_NUM_CHEQUE NVARCHAR(100) NOT NULL DEFAULT '',
	DESCRIPCION NVARCHAR(1000) NOT NULL DEFAULT '',
	COSTO NUMERIC(38, 2) NOT NULL DEFAULT 0.00,
	ESTADO INT NOT NULL DEFAULT 1,
	BAJA DATE NOT NULL DEFAULT GETDATE(),
	DESC_BAJA NVARCHAR(1000) NOT NULL DEFAULT '',
	ID_USUARIO INT NOT NULL DEFAULT 1,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO


CREATE TABLE Activos_Fijos.TBL_ASIGNACION_ACTIVO_FIJO_ENC
(
	ID NUMERIC(38, 0) NOT NULL,
		CONSTRAINT PK_TBL_ASIGNACION_ACTIVO_FIJO_ENC_ID PRIMARY KEY CLUSTERED(ID),
	ID_EMPLEADO INT NOT NULL,
		CONSTRAINT FX_TBL_ASIGNACION_ACTIVO_FIJO_ENC_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES Activos_Fijos.TBL_EMPLEADO(ID),
	ID_TIPO_MOVIMIENTO INT NOT NULL,
		CONSTRAINT FX_TBL_ASIGNACION_ACTIVO_FIJO_ENC_ID_TIPO_MOVIMIENTO FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES Activos_Fijos.TBL_TIPO_MOVIMIENTO(ID),
	FECHA DATE NOT NULL DEFAULT GETDATE(),
	OBSERVACIONES NVARCHAR(1000) NOT NULL DEFAULT '',
	ESTADO INT NOT NULL DEFAULT 1,
	BAJA DATE NOT NULL DEFAULT GETDATE(),
	DESC_BAJA NVARCHAR(1000) NOT NULL DEFAULT '',
	ID_USUARIO INT NOT NULL DEFAULT 1,
	FECHA_GRAB DATE NOT NULL DEFAULT GETDATE(),
	FECHA_MOD DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE Activos_Fijos.TBL_ASIGNACION_ACTIVO_FIJO_DET
(
	ID NUMERIC(38, 0) NOT NULL,
		CONSTRAINT PK_TBL_ASIGNACION_ACTIVO_FIJO_DET_ID PRIMARY KEY CLUSTERED(ID),
	ID_ENC NUMERIC(38, 0) NOT NULL,
		CONSTRAINT FX_TBL_ASIGNACION_ACTIVO_FIJO_DET_ID_ENC FOREIGN KEY (ID_ENC) REFERENCES Activos_Fijos.TBL_ASIGNACION_ACTIVO_FIJO_ENC(ID),
	ID_ARTICULO INT NOT NULL,
		CONSTRAINT FX_TBL_ASIGNACION_ACTIVO_FIJO_DET_ID_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES Activos_Fijos.TBL_ARTICULO(ID),
	COSTO NUMERIC(38, 2) NOT NULL DEFAULT 0.00,
	OBSERVACIONES NVARCHAR(1000) NOT NULL DEFAULT '',
);
GO