
USE MASTER
GO

CREATE DATABASE DB_ASIGNACION_ACTIVOS_FIJOS
ON 
(  
    NAME = DB_ASIGNACION_ACTIVOS_FIJOS_data,
    FILENAME = 'D:\Aplicaciones\ASIGNACION_ACTIVOS_FIJOS\DATOS\DB_ASIGNACION_ACTIVOS_FIJOS_data.mdf',
    SIZE = 10,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5  
)
LOG ON
( 
    NAME = DB_ASIGNACION_ACTIVOS_FIJOS_log,
    FILENAME = 'D:\Aplicaciones\ASIGNACION_ACTIVOS_FIJOS\DATOS\DB_ASIGNACION_ACTIVOS_FIJOS_log.ldf',
    SIZE = 10,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5  
);
GO